  FILE DRIVER = 0d35cd8e-97ea-4f9a-96af-0f0d89f76567 {
    SECTION DXE_DEPEX = Dxe/UFSDxe/UFSDxe.depex
    SECTION PE32 = Dxe/UFSDxe/UFSDxe.efi
    SECTION UI = "UFSDxe"
  }

  FILE DRIVER = 2a7b4bef-80cd-49e1-b473-374ba4d673fc {
    SECTION DXE_DEPEX = Dxe/SPMI/SPMI.depex
    SECTION PE32 = Dxe/SPMI/SPMI.efi
    SECTION UI = "SPMI"
  }

  FILE DRIVER = f541d663-4a48-40aa-aabf-ff158ccae34c {
    SECTION DXE_DEPEX = Dxe/SmemDxe/SmemDxe.depex
    SECTION PE32 = Dxe/SmemDxe/SmemDxe.efi
    SECTION UI = "SmemDxe"
  }

  FILE DRIVER = 4DB5DEA6-5302-4D1A-8A82-677A683B0D29 {
    SECTION DXE_DEPEX = Dxe/ClockDxe/ClockDxe.depex
    SECTION PE32 = Dxe/ClockDxe/ClockDxe.efi
    SECTION UI = "ClockDxe"
  }

  FILE DRIVER = 11faed4c-b21f-4d88-8e48-c4c28a1e50df {
    SECTION DXE_DEPEX = Dxe/UsbPwrCtrlDxe/UsbPwrCtrlDxe.depex
    SECTION PE32 = Dxe/UsbPwrCtrlDxe/UsbPwrCtrlDxe.efi
    SECTION UI = "UsbPwrCtrlDxe"
  }

  FILE DRIVER = 94f8a6a7-dc34-4101-88c1-99179cceae83 {
    SECTION DXE_DEPEX = Dxe/UsbfnDwc3Dxe/UsbfnDwc3Dxe.depex
    SECTION PE32 = Dxe/UsbfnDwc3Dxe/UsbfnDwc3Dxe.efi
    SECTION UI = "UsbfnDwc3Dxe"
  }

  FILE DRIVER = cd823a4d-7dec-4531-ae5d-4134fa4127b8 {
    SECTION DXE_DEPEX = Dxe/UsbConfigDxe/UsbConfigDxe.depex
    SECTION PE32 =Dxe/UsbConfigDxe/UsbConfigDxe.efi
    SECTION UI = "UsbConfigDxe"
  }

  FILE DRIVER = 0A134F0E-075E-40B3-9C63-3B3906804663 {
    SECTION DXE_DEPEX = Dxe/UsbInitDxe/UsbInitDxe.depex
    SECTION PE32 = Dxe/UsbInitDxe/UsbInitDxe.efi
    SECTION UI = "UsbInitDxe"
  }

  FILE DRIVER = 3299a266-15f0-4346-8318-716336736d3e {
    SECTION DXE_DEPEX = Dxe/UsbDeviceDxe/UsbDeviceDxe.depex
    SECTION PE32 = Dxe/UsbDeviceDxe/UsbDeviceDxe.efi
    SECTION UI = "UsbDeviceDxe"
  }

  FILE DRIVER = 2D2E62CF-9ECF-43B7-8219-94E7FC713DFE {
    SECTION PE32 = Dxe/UsbKbDxe/UsbKbDxe.efi
    SECTION UI = "UsbKbDxe"
  }

  FILE DRIVER = 5AF77F10-90DF-4E7E-8325-A17EC09D5443{
    SECTION DXE_DEPEX = Dxe/UsbMsdDxe/UsbMsdDxe.depex
    SECTION PE32 = Dxe/UsbMsdDxe/UsbMsdDxe.efi
    SECTION UI = "UsbMsdDxe"
  }

 # FILE DRIVER = 8e9bd160-b184-11df-94e2-0800200c9a66 {
 #    SECTION DXE_DEPEX = Dxe/DALSys/DALSys.depex
 #    SECTION PE32 = Dxe/DALSys/DALSys.efi
 #    SECTION UI = "DALSys"
 # }

 FILE DRIVER = 5776232E-082D-4B75-9A0E-FE1D13F7A5D9 {
    SECTION DXE_DEPEX = Dxe/PmicDxe/PmicDxeLa.depex
    SECTION PE32 = Dxe/PmicDxe/PmicDxeLa.efi
    SECTION UI = "PmicDxe"
 }

 FILE DRIVER = 5bd181db-0487-4f1a-ae73-820e165611b3 {
    SECTION DXE_DEPEX = Dxe/ButtonsDxe/ButtonsDxe.depex
    SECTION PE32 = Dxe/ButtonsDxe/ButtonsDxe.efi
    SECTION UI = "ButtonsDxe"
 }

 # FILE DRIVER =240612B7-A063-11d4-9A3A-0090273FC14D {
 #   SECTION DXE_DEPEX = Dxe/usb/XhciDxe/XhciDxe.depex
 #   SECTION PE32 = Dxe/all/UsbBusDxe.efi
 #   SECTION UI = "UsbBusDxe"
 # }
